CREATE TABLE [dbo].[Book]
(
	[ISBN] INT NOT NULL PRIMARY KEY, 
    [Title] NVARCHAR(MAX) NOT NULL, 
    [PubYear] INT NOT NULL, 
    [AID] INT NOT NULL FOREIGN KEY REFERENCES Author,
	[SID] INT NOT NULL FOREIGN KEY REFERENCES Student
)
