CREATE TABLE [dbo].[Book]
(
	[ISBN] NVARCHAR(50) NOT NULL PRIMARY KEY, 
    [Title] NVARCHAR(MAX) NOT NULL, 
    [PubYear] INT NOT NULL, 
    [AID] INT NOT NULL FOREIGN KEY REFERENCES Author,
	[SID] VARCHAR(50) FOREIGN KEY REFERENCES Student
)
