CREATE TABLE [dbo].[Student]
(
	[SID] VARCHAR(50) NOT NULL PRIMARY KEY, 
    [FName] CHAR(25) NOT NULL, 
    [LName] CHAR(25) NOT NULL, 
    [Email] NVARCHAR(MAX) NOT NULL, 
    [MobileNo] VARCHAR(50) NOT NULL
)
